CREATE TABLE events_list (
    id INT AUTO_INCREMENT PRIMARY KEY,
    is_showing BOOLEAN DEFAULT FALSE,
    poster_name VARCHAR(255),
    poster_type VARCHAR(100),
    poster_size INT,
    poster_data LONGBLOB,
    qrcode_name VARCHAR(255),
    qrcode_type VARCHAR(100),
    qrcode_size INT,
    qrcode_data LONGBLOB,
    event_name VARCHAR(255) NOT NULL,
    short_details TEXT NOT NULL,
    about_event TEXT NOT NULL,
    event_date DATE NOT NULL,
    event_start_time TIME NOT NULL,
    event_end_time TIME NOT NULL,
    event_location VARCHAR(255) NOT NULL,
    event_category VARCHAR(50) NOT NULL,
    event_organiser VARCHAR(255) NOT NULL,
    admin_contact VARCHAR(255) NOT NULL,
    public_contact VARCHAR(255) NOT NULL,
    event_type ENUM('free','paid') DEFAULT 'free',
    what_to_expect TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

